version: '3'
services:
  api:
    build: 
      context: ${API}
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - PORT=3000
    volumes:
      - /usr/src/app/node_modules
      - ${API}:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: 
      context: ${APP}
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ${APP}:/app
    environment:
      - NODE_ENV=development
      # - BACKEND_URL=http://localhost:3001
      # - BACKEND_URL=http://host.docker.internal:3001
      - BACKEND_URL=http://demo1.localhost
  
  web:
    image: nginx:1.17.10
    depends_on:
      - app
      - api
    volumes:
      - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
    command: /bin/bash -c "envsubst '' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
volumes:
  postgres_data:
